default_stages: [commit, push]
default_language_version:
  python: python3.8
repos:
  - repo: local
    hooks:
      - id: Obsidian Formatting to Quartz Compliant Format
        name: main.py
        entry: python3 main.py
        language: system
        types: [python]
        always_run: true
