repos:
  - repo: local
    hooks:
      - id: Obsidian Formatting to Quartz Compliant Format
        name: main.py
        entry: python main.py
        language: system
        types: [python]
        always_run: true
